/** Situations de découverte pour la classe de seconde. Aucun calcul. */

const decouverteBrutes = [
  {
    id: 'dec_z01',
    theme: 'zones',
    question: 'Où le camion se met-il pour être déchargé ?',
    options: ['Au quai de réception', 'Dans le bureau du chef', 'Sur le parking des voitures', 'Dans la salle de pause'],
    correctOption: 0,
    explanation: 'Le quai est l’endroit où le camion est déchargé ou chargé.',
  },
  {
    id: 'dec_z02',
    theme: 'zones',
    question: 'Comment s’appelle l’endroit où les produits attendent d’être rangés après le contrôle ?',
    options: ['La zone de stockage ou d’attente', 'La cafétéria', 'Le vestiaire', 'Le local poubelles'],
    correctOption: 0,
    explanation: 'Après le contrôle, la marchandise attend dans une zone prévue avant d’être rangée.',
  },
  {
    id: 'dec_z03',
    theme: 'zones',
    question: 'À quoi sert une allée d’entrepôt ?',
    options: ['À circuler et à accéder aux emplacements', 'À garer les voitures des visiteurs', 'À manger', 'À ranger les dossiers du secrétariat'],
    correctOption: 0,
    explanation: 'Les allées permettent aux personnes et aux engins d’atteindre les emplacements.',
  },
  {
    id: 'dec_z04',
    theme: 'zones',
    question: 'Que trouve-t-on en général sur un quai d’expédition ?',
    options: ['Les commandes prêtes à partir', 'Les outils de la comptabilité', 'Les menus de la cantine', 'Les copies d’examen'],
    correctOption: 0,
    explanation: 'Le quai d’expédition regroupe ce qui doit être chargé dans les camions.',
  },
  {
    id: 'dec_z05',
    theme: 'zones',
    question: 'Pourquoi peint-on des passages piétons dans l’entrepôt ?',
    options: ['Pour séparer les piétons des engins', 'Pour décorer le sol', 'Pour indiquer la cafétéria', 'Pour mesurer les palettes'],
    correctOption: 0,
    explanation: 'Le marquage au sol montre où les personnes peuvent marcher sans croiser un engin.',
  },
  {
    id: 'dec_z06',
    theme: 'zones',
    question: 'Un emplacement de stockage sert à :',
    options: ['Ranger une marchandise à une adresse précise', 'Accueillir les parents d’élèves', 'Stocker les extincteurs uniquement', 'Garer le camion du directeur'],
    correctOption: 0,
    explanation: 'Chaque produit a une adresse : allée, travée, niveau.',
  },
  {
    id: 'dec_z07',
    theme: 'zones',
    question: 'La zone d’emballage se situe plutôt :',
    options: ['Avant le quai de départ', 'Dans le parking extérieur', 'Au vestiaire', 'Dans la salle des professeurs'],
    correctOption: 0,
    explanation: 'On prépare et on ferme les colis avant de les mettre sur le quai de départ.',
  },
  {
    id: 'dec_z08',
    theme: 'zones',
    question: 'Que ne doit-on pas laisser devant une issue de secours ?',
    options: ['Une palette ou un chariot', 'Un panneau de signalisation', 'Un extincteur', 'Un marquage au sol'],
    correctOption: 0,
    explanation: 'L’issue de secours doit rester libre pour sortir en cas d’urgence.',
  },
  {
    id: 'dec_s01',
    theme: 'securite',
    question: 'Que porte-t-on aux pieds dans un entrepôt ?',
    options: ['Des chaussures de sécurité', 'Des sandales', 'Des chaussons', 'Des baskets trouées'],
    correctOption: 0,
    explanation: 'Les chaussures de sécurité protègent des chutes d’objets et des écrasements.',
  },
  {
    id: 'dec_s02',
    theme: 'securite',
    question: 'À quoi sert un gilet haute visibilité ?',
    options: ['À être vu par les conducteurs d’engins', 'À avoir moins froid', 'À porter plus lourd', 'À remplacer un casque'],
    correctOption: 0,
    explanation: 'Le gilet permet d’être repéré dans les allées et sur les quais.',
  },
  {
    id: 'dec_s03',
    theme: 'securite',
    question: 'Un pictogramme jaune triangulaire annonce en général :',
    options: ['Un danger', 'Une sortie', 'Un bureau', 'Une cantine'],
    correctOption: 0,
    explanation: 'Le triangle jaune est un signal d’avertissement.',
  },
  {
    id: 'dec_s04',
    theme: 'securite',
    question: 'Avant de soulever un carton lourd, on :',
    options: ['Plie les genoux et garde le dos droit', 'Tire avec le dos arrondi', 'Court avec le carton', 'Le lance au collègue'],
    correctOption: 0,
    explanation: 'Plier les genoux limite le mal de dos. Au-delà, on demande une aide ou un engin.',
  },
  {
    id: 'dec_s05',
    theme: 'securite',
    question: 'Pourquoi ne marche-t-on pas sous une charge levée ?',
    options: ['Parce qu’elle peut tomber', 'Parce que c’est plus long', 'Parce que le sol est mouillé exprès', 'Parce que c’est réservé aux visiteurs'],
    correctOption: 0,
    explanation: 'Une charge en hauteur peut chuter. On reste à l’écart.',
  },
  {
    id: 'dec_s06',
    theme: 'securite',
    question: 'Que faire si un produit est répandu dans l’allée ?',
    options: ['Prévenir et baliser la zone', 'Courir dessus', 'Le cacher avec une palette', 'Continuer sans rien dire'],
    correctOption: 0,
    explanation: 'Une flaque ou un produit au sol est un risque de chute. On prévient et on signale.',
  },
  {
    id: 'dec_s07',
    theme: 'securite',
    question: 'Les gants de manutention protègent surtout :',
    options: ['Les mains', 'Les oreilles', 'Les yeux seulement', 'Les cheveux'],
    correctOption: 0,
    explanation: 'Les gants limitent les coupures et les accrocs pendant la manutention.',
  },
  {
    id: 'dec_s08',
    theme: 'securite',
    question: 'Un extincteur sert :',
    options: ['À attaquer un début d’incendie si on est formé', 'À caler une porte', 'À mesurer une palette', 'À éclairer le quai'],
    correctOption: 0,
    explanation: 'L’extincteur est un moyen de secours. On ne l’utilise que si on sait le faire, sinon on alerte.',
  },
  {
    id: 'dec_a01',
    theme: 'acteurs',
    question: 'Qui fabrique ou fournit la marchandise au départ ?',
    options: ['Le fournisseur', 'Le client final', 'Le gardien du parking', 'L’élève en stage le premier jour'],
    correctOption: 0,
    explanation: 'Le fournisseur est en amont : il envoie les produits.',
  },
  {
    id: 'dec_a02',
    theme: 'acteurs',
    question: 'Qui transporte la marchandise d’un site à un autre ?',
    options: ['Le transporteur', 'Le magasinier qui range', 'Le client qui attend', 'Le responsable de la paie'],
    correctOption: 0,
    explanation: 'Le transporteur déplace les marchandises, souvent par camion.',
  },
  {
    id: 'dec_a03',
    theme: 'acteurs',
    question: 'Qui reçoit la commande à la fin ?',
    options: ['Le destinataire, ou client', 'Le fabricant de palettes', 'Le peintre des allées', 'Le livreur de pizzas'],
    correctOption: 0,
    explanation: 'Le destinataire est celui à qui la marchandise doit arriver.',
  },
  {
    id: 'dec_a04',
    theme: 'acteurs',
    question: 'Dans un entrepôt, le magasinier :',
    options: ['Réceptionne, range, prépare ou expédie', 'Conduit uniquement les bus', 'Rédige les bulletins de notes', 'Répare les routes'],
    correctOption: 0,
    explanation: 'Le magasinier agit sur les flux dans l’entrepôt.',
  },
  {
    id: 'dec_a05',
    theme: 'acteurs',
    question: 'Un flux physique, c’est :',
    options: ['Le déplacement des produits', 'Un e-mail sans colis', 'Une réunion', 'Une pause'],
    correctOption: 0,
    explanation: 'Le flux physique est le mouvement réel de la marchandise.',
  },
  {
    id: 'dec_a06',
    theme: 'acteurs',
    question: 'Un flux d’information, c’est par exemple :',
    options: ['L’envoi du bon de livraison', 'Le trajet de la palette', 'Le bruit du chariot', 'Le poids du camion'],
    correctOption: 0,
    explanation: 'Les documents et les messages disent ce qui bouge, où et pour qui.',
  },
  {
    id: 'dec_a07',
    theme: 'acteurs',
    question: 'Pourquoi note-t-on le nom du transporteur sur le quai ?',
    options: ['Pour savoir qui prend ou livre la marchandise', 'Pour choisir la musique', 'Pour compter les pauses', 'Pour décorer le bureau'],
    correctOption: 0,
    explanation: 'Identifier le transporteur évite de charger ou décharger le mauvais camion.',
  },
  {
    id: 'dec_a08',
    theme: 'acteurs',
    question: 'Le client commande. L’entrepôt :',
    options: ['Prépare et fait partir les produits demandés', 'Fabrique toujours l’acier', 'Change le prix de l’essence', 'Annule la livraison sans lire la commande'],
    correctOption: 0,
    explanation: 'L’entrepôt répond à la commande en préparant les bons produits.',
  },
  {
    id: 'dec_d01',
    theme: 'documents',
    question: 'Le bon de livraison accompagne :',
    options: ['La marchandise envoyée', 'Le menu de la cantine', 'Le badge visiteur uniquement', 'Le planning des vacances'],
    correctOption: 0,
    explanation: 'Le bon de livraison liste ce qui est envoyé au destinataire.',
  },
  {
    id: 'dec_d02',
    theme: 'documents',
    question: 'À la réception, on compare le camion avec :',
    options: ['Le bon de livraison ou la commande', 'Le règlement intérieur du collège', 'La météo', 'Le catalogue de vêtements'],
    correctOption: 0,
    explanation: 'On vérifie que les produits reçus correspondent aux documents.',
  },
  {
    id: 'dec_d03',
    theme: 'documents',
    question: 'Si un colis est abîmé à l’arrivée, on :',
    options: ['Le signale et on note des réserves', 'On le cache', 'On le jette sans rien dire', 'On change l’étiquette pour un autre produit'],
    correctOption: 0,
    explanation: 'Les réserves décrivent le problème au moment de la réception.',
  },
  {
    id: 'dec_d04',
    theme: 'documents',
    question: 'Une étiquette sur un colis sert d’abord à :',
    options: ['Identifier le produit et sa destination', 'Décorer le carton', 'Indiquer l’heure de la pause', 'Remplacer la chaussure de sécurité'],
    correctOption: 0,
    explanation: 'L’étiquette dit ce que c’est et où cela doit aller.',
  },
  {
    id: 'dec_d05',
    theme: 'documents',
    question: 'Cocher les quantités reçues permet de :',
    options: ['Voir s’il manque des pièces', 'Choisir la couleur du quai', 'Calculer la note de maths', 'Fermer l’entrepôt'],
    correctOption: 0,
    explanation: 'Le contrôle quantitatif vérifie le nombre de colis ou d’articles.',
  },
  {
    id: 'dec_d06',
    theme: 'documents',
    question: 'Le nom et l’adresse sur un colis indiquent :',
    options: ['Le destinataire', 'Le goût du produit', 'La pointure du cariste', 'L’âge du chauffeur'],
    correctOption: 0,
    explanation: 'Sans destinataire lisible, le colis ne peut pas partir au bon endroit.',
  },
  {
    id: 'dec_d07',
    theme: 'documents',
    question: 'Pourquoi garde-t-on une trace de la réception ?',
    options: ['Pour retrouver qui a reçu quoi, et quand', 'Pour effacer l’historique', 'Pour éviter d’écrire', 'Pour jeter les documents tout de suite'],
    correctOption: 0,
    explanation: 'La trace sert en cas de litige ou de recherche.',
  },
  {
    id: 'dec_d08',
    theme: 'documents',
    question: 'Un produit sans étiquette lisible :',
    options: ['Doit être signalé avant d’être rangé au hasard', 'Peut être mélangé avec n’importe quoi', 'Est forcément périmé', 'Part en premier'],
    correctOption: 0,
    explanation: 'Sans identification, on ne sait pas où ranger ni quoi préparer.',
  },
  {
    id: 'dec_m01',
    theme: 'manutention',
    question: 'Une palette sert à :',
    options: ['Regrouper des colis pour les déplacer ensemble', 'Écrire au tableau', 'Manger assis', 'Remplacer un extincteur'],
    correctOption: 0,
    explanation: 'La palette est un support qui porte plusieurs colis.',
  },
  {
    id: 'dec_m02',
    theme: 'manutention',
    question: 'Une palette Europe mesure environ :',
    options: ['80 cm sur 120 cm', '20 cm sur 20 cm', '2 m sur 4 m', 'La taille d’une feuille A4'],
    correctOption: 0,
    explanation: 'La palette Europe courante fait 80 × 120 cm. On la reconnaît, on ne calcule pas encore son chargement.',
  },
  {
    id: 'dec_m03',
    theme: 'manutention',
    question: 'Un carton fermé et étiqueté est :',
    options: ['Un colis', 'Un quai', 'Un transporteur', 'Un pictogramme'],
    correctOption: 0,
    explanation: 'Le colis est l’unité que l’on prépare, déplace et expédie.',
  },
  {
    id: 'dec_m04',
    theme: 'manutention',
    question: 'Pour déplacer plusieurs cartons lourds, on utilise plutôt :',
    options: ['Un chariot ou un transpalette', 'Ses dents', 'Une chaise de bureau', 'Un parapluie'],
    correctOption: 0,
    explanation: 'L’engin ou le chariot évite de porter trop lourd à la main.',
  },
  {
    id: 'dec_m05',
    theme: 'manutention',
    question: 'Gerber, c’est :',
    options: ['Empiler de façon stable', 'Jeter au sol', 'Mélanger deux commandes', 'Effacer une étiquette'],
    correctOption: 0,
    explanation: 'On empile seulement si la charge du dessous supporte celle du dessus.',
  },
  {
    id: 'dec_m06',
    theme: 'manutention',
    question: 'Pourquoi ne charge-t-on pas un camion « comme ça vient » ?',
    options: ['Pour que rien ne tombe et que le bon client soit livré', 'Pour aller plus vite sans regarder', 'Pour cacher les colis abîmés', 'Pour laisser des trous au milieu'],
    correctOption: 0,
    explanation: 'L’ordre de chargement protège les produits et respecte les destinations.',
  },
  {
    id: 'dec_m07',
    theme: 'manutention',
    question: 'Un film autour d’une palette sert à :',
    options: ['Maintenir les colis ensemble', 'Remplacer l’adresse', 'Cacher un trou dans le carton sans le dire', 'Indiquer l’heure'],
    correctOption: 0,
    explanation: 'Le filmage stabilise la charge pendant le déplacement.',
  },
  {
    id: 'dec_m08',
    theme: 'manutention',
    question: 'Avant de prendre un colis, on regarde :',
    options: ['L’étiquette et l’état du carton', 'Uniquement la couleur du scotch', 'Le prénom du chauffeur', 'La fenêtre'],
    correctOption: 0,
    explanation: 'L’étiquette dit quoi prendre. L’état du carton dit si le produit est abîmé.',
  },
]

function disperser(question, index) {
  const cible = index % 4
  if (cible === question.correctOption) return question
  const options = [...question.options]
  const bonne = options[question.correctOption]
  options.splice(question.correctOption, 1)
  options.splice(cible, 0, bonne)
  return { ...question, options, correctOption: cible }
}

export const decouverteQuestions = decouverteBrutes.map(disperser)

export function questionsDecouverte(theme) {
  if (!theme) return decouverteQuestions
  const pool = decouverteQuestions.filter((question) => question.theme === theme)
  return pool.length ? pool : decouverteQuestions
}
